{% set version = "2.1-7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mlbench
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://cran.r-project.org/src/contrib/mlbench_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/mlbench/mlbench_{{ version }}.tar.gz
  sha256: 7669e35715721d0dc412380747ba36f5a2fd63938851a289de815bbe91d8015c

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("c") }}                # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('mlbench')"  # [not win]
    - "\"%R%\" -e \"library('mlbench')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mlbench
  license: GPL-2.0-only
  summary: A collection of artificial and real-world machine learning benchmark problems, including, e.g., several data sets from the UCI repository.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
