travis:
  secure:
    BINSTAR_TOKEN: gogSORRBp2NHGQgVGCzxIs49b9s8X1x+puFUKolK4y+bwMRaYRgzP8oHKAhzuY+1KI7mxnVxss/SbWTWAwFK0iF7SmLlL+7zXO/L+0eYj9df3pMVi6Xd3wGbrgTfsk+xtRxFxE44F8QWf8TxpSICaEEaOskCxeQp1DkK7nplay9RAvxgCzp79CxFb9yYSNO+kEULT7yIQBszxhu3k9gZbLu5cE3bWrGvKk4pJDQXoChRJOV21l13CSjxGTID0MZs44sDS1I+4BMcEKRyBulZB06HFUq6/vFEGWVggu1JX56AldqQUWBL09FhYMYnRaLScCTYpRSm9cItlaFMjk2dw/OkICxIlkGY2Oml1ugk8ktmTAPTdsqLs1AOLvqfftQNwSbsg7GheCAq9f7jadmwL8FhPYPuSsj66xKBFEioIv6fe0Bqt8O+b2PEglfgQSsI0M7IjQFS2CuTsGYOb6d46s0RZKKGNfeIImdw3bMdHxUrqL2k+4lZaZGFd0YdIzJaiDSXFXgmNC+4471Ni6ODChXaOriVQqmGuzsjn9F2+ihfKk3qmwIAAhuf1kbojbu18QPx0ECZsJsL0cOSGafv10zlcfuSMhMSRyq4Hwc9zHU1NShxVpW4lHUbRPBBi37WgXnDH0gFDvNAlL0o6uXMi/+nGEaGZlhAW3ys9+HrdYA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
