appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: xnkxzBRrh8LlI8EEtCUoPGPSOpGnW5pnYUtc6Z4RcGDedyAFux0S0eGc5uWgL8RjOMyJnFEVQWNvxvIJ6TrwnHeyLbt2sf778NLCzWOBNDveXcyNxoubw7WtSWNJyWaOU80GWsM5arXDneRjV+wtmlAUh2mckH7yytFcbDFs3PxGMUdXUKryo9v9ltILllj5464/uJ6Y/Jb4pqlff+tEtA8uQ8YDL5d8oKPTZvbEm9Tci6jXbJGSovsqM4RxPdfR3JYrKjAFbl1QAadQHuNLdwiedkNi+36fXn9/rumPsTKvuCSsH/8EAah70Z/ZetMd0qKNu+8mmVsCIu5bAoRIs4FtigTVpnvJuhiPKSTQo75jFkkPHEGbfTQjtCAHGD183zfMK45ZUjExBS7j0y2tDKQh/x9yGJ5jeVG4bBM2Rt7izDoaD0xZVEP2Z4Axn0+rgIfQI5GhnJd2q1A7oJU/UlG/IidcERz9tQrBk0GHsdeVVWQn5MauQYhHYDFjkJKUps7+PePr6d3F2XsIgU8Ve1BkYKPGnRwbUZyJgQuSv4jvkZuwLJULaPdUvfljkFlgBEzGC7OKTOrfpHKBWu22tDp0Hem7eyVGx8bueHGRI3FklhZRLH2izWQqIpSS86cAxLrP2Sz7u+/AAOTVqW8w7tKTHA6ZxuLhs+78I2eWrr8=}
